################################################################
# API and dashboard configuration
################################################################
[api]
################################################################
# Consul Catalog
################################################################
[consulCatalog]
endpoint = "consul:8500"
exposedByDefault = true
prefix = "traefik"
domain = "docker.localhost"